config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"

  # Root route
  # root "render#index"

  resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :comments, only: [:create, :edit, :update, :destroy] do
      resources :likes, only: [:create, :destroy], defaults: { likeable: 'Comment' }
      resources :replies, controller: 'comments', only: [:create, :edit, :update, :destroy]
    end
    resources :likes, only: [:create, :destroy], defaults: { likeable: 'Post' }
    resource :save_post, only: [:create, :destroy], as: :save, path: 'save'
  end

  patch '/posts/:id/unpublish', to: 'posts#unpublish', as: :unpublish_post

  get 'signup', to: 'users#new', as: 'signup'

  resources :users, only: [:show, :edit, :update] do
    member do
      get :posts  # This route allows users to manage their posts
      get :saved_posts # This route allows users to view their saved posts
    end
    resource :profile, only: [:show, :edit, :update]
    resources :donations, only: [:index], module: :users
  end

  delete "/tags/:id", to: "tags#destroy", as: :tag
  resources :maps

  authenticated :user do
    root 'dashboard#show', as: :authenticated_root
  end

  namespace :admin do
    # put your admin routes here
    get 'dashboard/weekly_donations', to: 'dashboard#weekly_donations'
    root to: "dashboard#index" # Example admin dashboard route
    resources :users do
      collection do
        get 'search'
      end
      member do
        patch :suspend
        patch :unsuspend
        delete :destroy
      end
    end
    resources :posts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :series, only: [:index, :new, :create, :edit, :update, :show]


  resources :reports, only: [:index, :show, :edit, :update, :destroy, :new, :create] do
    member do
      delete 'destroy_comment'
    end
  end

  get 'moderation', to: 'moderation#index'

  get "up" => "rails/health#show", as: :rails_health_check

  resources :notifications, only: [:index, :destroy] do
    member do
      patch :mark_as_read
    end
  end

  resources :donations, only: [:new, :create]
  post 'webhooks/stripe', to: 'webhooks#stripe'

  resources :donations do
    collection do
      get 'success'
      get 'cancel'
    end
  end

  resources :feedbacks, only: [:new, :create]


  post 'newsletter/subscribe', to: 'newsletters#subscribe', as: 'newsletter_subscribe'
  get 'newsletter/unsubscribe', to: 'newsletters#confirm_unsubscribe', as: 'confirm_unsubscribe_newsletter'
  delete 'newsletter/unsubscribe', to: 'newsletters#unsubscribe', as: 'unsubscribe_newsletter'

end

app/views/shared/_footer.html.erb
<footer class="bg-gray-900" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="mx-auto max-w-7xl px-6 pb-8 pt-20 sm:pt-24 lg:px-8 lg:pt-32">
    <div class="xl:grid xl:grid-cols-3 xl:gap-8">
      <div class="grid grid-cols-2 gap-8 xl:col-span-2">
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold leading-6 text-white">Solutions</h3>
            <ul role="list" class="mt-6 space-y-4">
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Marketing</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Analytics</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Commerce</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Insights</a>
              </li>
            </ul>
          </div>
          <div class="mt-10 md:mt-0">
            <h3 class="text-sm font-semibold leading-6 text-white">Support</h3>
            <ul role="list" class="mt-6 space-y-4">
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Pricing</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Documentation</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Guides</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">API Status</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="md:grid md:grid-cols-2 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold leading-6 text-white">Company</h3>
            <ul role="list" class="mt-6 space-y-4">
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">About</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Blog</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Jobs</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Press</a>
              </li>
              <li>
                <a href="#" class="text-sm leading-6 text-gray-300 hover:text-white">Partners</a>
              </li>
            </ul>
          </div>
          <div class="mt-10 md:mt-0">
            <h3 class="text-sm font-semibold leading-6 text-white">Nous faire part d'un retour</h3>
            <div class="mt-6 space-y-4">
              <%= link_to 'Envoyer un retour', new_feedback_path, class: 'flex w-full items-center cursor-pointer justify-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"' %>
            </div>
          </div>
        </div>
      </div>
      <div class="mt-10 xl:mt-0">
        <h3 class="text-sm font-semibold leading-6 text-white">Subscribe to our newsletter</h3>
        <p class="mt-2 text-sm leading-6 text-gray-300">The latest news, articles, and resources, sent to your inbox weekly.</p>
        <!-- Render the newsletter form partial here -->
        <%= render 'shared/newsletter_form' %>
      </div>
    </div>
    <div class="mt-16 border-t border-white/10 pt-8 sm:mt-20 md:flex md:items-center md:justify-between lg:mt-24">
      <div class="flex space-x-6 md:order-2">
        <a href="#" class="text-gray-500 hover:text-gray-400">
          <span class="sr-only">Facebook</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
          </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-400">
          <span class="sr-only">Instagram</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
          </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-400">
          <span class="sr-only">X</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path d="M13.6823 10.6218L20.2391 3H18.6854L12.9921 9.61788L8.44486 3H3.2002L10.0765 13.0074L3.2002 21H4.75404L10.7663 14.0113L15.5685 21H20.8131L13.6819 10.6218H13.6823ZM11.5541 13.0956L10.8574 12.0991L5.31391 4.16971H7.70053L12.1742 10.5689L12.8709 11.5655L18.6861 19.8835H16.2995L11.5541 13.096V13.0956Z" />
          </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-400">
          <span class="sr-only">GitHub</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
          </svg>
        </a>
        <a href="#" class="text-gray-500 hover:text-gray-400">
          <span class="sr-only">YouTube</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418ZM15.194 12 10 15V9l5.194 3Z" clip-rule="evenodd" />
          </svg>
        </a>
      </div>
      <p class="mt-8 text-xs leading-5 text-gray-400 md:order-1 md:mt-0">&copy; 2020 Your Company, Inc. All rights reserved.</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-white sticky top-0 z-40" data-controller="header">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button data-header-target="openMobileUserMenu" type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-900 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-between sm:items-stretch sm:justify-between">
        <%= link_to root_path do  %>
          <div class="flex flex-shrink-0 items-center">
            <img class="h-12 w-auto" src="<%= image_path('captainruby-logo.png') %>" alt="Logo Captain Ruby">
            <%# <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company"> %>
          </div>
        <% end %>
        <div
          class="hidden sm:ml-6 sm:block"

        >
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <% if user_signed_in? %>
              <p class="text-white"><%= current_user.email %></p>
              <p class="text-white"><%= current_user.full_name %></p>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "Acceuil", root_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
              <% if current_user.has_role?(:admin) || current_user.has_role?(:moderator) %>
                <%= link_to 'Dashboard', dashboard_show_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
              <% end %>
            <% else %>
              <%= link_to "Acceuil", root_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
            <% end %>
            <%= link_to "Map", maps_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
            <%= link_to "Faire un don", new_donation_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
            <% if user_signed_in? && current_user.has_role?(:admin) %>
              <%= link_to "Admin", admin_root_path, class: "text-gray-900 rounded-md px-3 py-2 text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">

      <% if user_signed_in? %>
        <div data-controller="notifications" class="relative">
          <button id="notification-bell" type="button" class="relative rounded-full  p-1 text-gray-900 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" data-action="click->notifications#toggle">
            <span class="sr-only">Voir mes notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
            <%= turbo_stream_from "notifications_#{current_user.id}_counter" %>
            <% if current_user.notifications.unread.count > 0 %>
              <span id="notification-counter" class="absolute -top-1 -right-1 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-red-100 bg-red-600 rounded-full">
                <%= current_user.notifications.unread.count %>
              </span>
            <% end %>
          </button>

          <div id="notification-lightbox" data-notifications-target="lightbox" class="hidden absolute right-0 mt-2 w-80 bg-white rounded-lg shadow-lg overflow-hidden z-50">
            <div class="p-4">
              <div class="flex items-center justify-between">
                <h2 class="text-lg font-semibold text-gray-700">Notifications</h2>
                <%= link_to "Tout voir", notifications_path, class: "text-gray-700" %>
              </div>
              <hr class="my-2">
              <div id="notification-dropdown-list" class="space-y-2 max-h-[30rem] overflow-y-auto">
                <%= turbo_stream_from "notifications_#{current_user.id}_dropdown_list" %>
                <% current_user.notifications.order(created_at: :desc).each do |notification| %>
                  <%= render partial: 'notifications/notification', locals: { notification: notification } %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>



        <!-- Profile dropdown -->
        <div class="relative ml-3">
          <div>
            <button data-header-target="openUserMenu" type="button" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <span class="sr-only">Open user menu</span>
              <img class="h-8 w-8 rounded-full object-cover"
                src="<%= if user_signed_in?
                          if current_user.profile.avatar.attached?
                            url_for(current_user.profile.avatar)
                          elsif current_user.profile.avatar.present?
                            current_user.profile.avatar
                          else
                            image_path('blank_pic.png')
                          end
                        else
                          image_path('blank_pic.png')
                        end %>"
                alt="User Avatar">
            </button>
          </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
          <div
            class=" hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
            id="menu-dropdown-items"
            role="menu"
            aria-orientation="vertical"
            aria-labelledby="user-menu-button"
            tabindex="-1"
            data-header-enter="transition ease-out duration-100"
            data-header-enter-start="transform opacity-0 scale-95"
            data-header-enter-end="transform opacity-100 scale-100"
            data-header-leave="transition ease-in duration-75"
            data-header-leave-start="transform opacity-100 scale-100"
            data-header-leave-end="transform opacity-0 scale-95"
          >
            <!-- Active: "bg-gray-100", Not Active: "" -->
            <% if user_signed_in? %>
              <%= link_to "Mon Profile", user_profile_path(current_user), class: "block px-4 py-2 text-sm text-gray-700" %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "block px-4 py-2 text-sm text-gray-700" %>
            <% else %>
              <%= link_to "S'inscrire", new_user_registration_path, class: "block px-4 py-2 text-sm text-gray-900" %>
              <%= link_to "Se connecter", new_user_session_path, class: "block px-4 py-2 text-sm text-gray-700" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div
    class=" hidden sm:hidden "
    <%# id="mobile-menu" %>
    id="mobile-menu-dropdown-items"
    data-header-target="menu"
    data-header-enter="transition ease-out duration-100"
    data-header-enter-start="transform opacity-0 scale-95"
    data-header-enter-end="transform opacity-100 scale-100"
    data-header-leave="transition ease-in duration-75"
    data-header-leave-start="transform opacity-100 scale-100"
    data-header-leave-end="transform opacity-0 scale-95"
  >
    <div class="z-10 fixed w-full bg-gray-700 space-y-1 px-2 pb-3 pt-2">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <%= link_to 'Dashboard', dashboard_show_path, class: "bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" %>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Team</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Projects</a>
      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Calendar</a>
    </div>
  </div>
</nav>

app/views/shared/_newsletter_form.html.erb
<% if user_signed_in? %>
  <% if @subscription.present? && @subscription.persisted? && @subscription.subscribed? %>
    <%= form_with url: unsubscribe_newsletter_path, method: :delete, local: true, class: "mt-6 sm:flex sm:max-w-md" do |f| %>
      <label for="email-address" class="sr-only">Email address</label>
      <%= f.hidden_field :email, value: @subscription.email %>
      <div class="mt-4 sm:ml-4 sm:mt-0 sm:flex-shrink-0">
        <%= f.submit "Se désabonner", class: "flex w-full items-center cursor-pointer justify-center rounded-md bg-red-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-500" %>
      </div>
    <% end %>
  <% else %>
    <%= form_with url: newsletter_subscribe_path, method: :post, local: true, class: "mt-6 sm:flex sm:max-w-md" do |f| %>
      <label for="email-address" class="sr-only">Email address</label>
      <%= f.email_field :email, value: current_user.email, placeholder: "Entrez votre email", class: "w-full min-w-0 appearance-none rounded-md border-0 bg-white/5 px-3 py-1.5 text-base text-white shadow-sm ring-1 ring-inset ring-white/10 placeholder:text-gray-500 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:w-64 sm:text-sm sm:leading-6 xl:w-full", required: true %>
      <div class="mt-4 sm:ml-4 sm:mt-0 sm:flex-shrink-0">
        <%= f.submit "S'abonner", class: "flex w-full items-center cursor-pointer justify-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <%= form_with url: new_user_session_path, method: :get, local: true, class: "mt-6 sm:flex sm:max-w-md" do |f| %>
    <label for="email-address" class="sr-only">Email address</label>
    <%= f.email_field :email, placeholder: "Entrez votre email", class: "w-full min-w-0 appearance-none rounded-md border-0 bg-white/5 px-3 py-1.5 text-base text-white shadow-sm ring-1 ring-inset ring-white/10 placeholder:text-gray-500 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:w-64 sm:text-sm sm:leading-6 xl:w-full", required: true %>
    <div class="mt-4 sm:ml-4 sm:mt-0 sm:flex-shrink-0">
      <%= f.submit "S'abonner", class: "flex w-full items-center cursor-pointer justify-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_searchbar.html.erb
<div class="flex justify-center items-center bg-white pb-2 sticky top-16 z-10 border-b-[1px] border-gray-300">
  <div class="w-80">
    <div class="relative mt-2 flex items-center cursor-pointer" id="quick-search" data-controller="search"
    data-action="click->search#showModal" data-modal-trigger-id="search-form">
      <div class="flex justify-between w-full rounded-md border-0 py-1.5 px-1 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 sm:text-sm sm:leading-6">
        <span>Rechercher un article...</span> <kbd class="ml-2 inline-flex items-center rounded border border-gray-200 px-1 font-sans text-xs text-gray-400">Ctrl K</kbd>
      </div>
    </div>
  </div>
</div>